
-- coke store
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 1, 'San pellegrino Momenti', 'Sanpellegrino momenti Pesca+Tea is the new low calorie, sparkling fruit drink that will add a burst of color to your moments', '3.00', '9', 70, 'https://laz-img-sg.alicdn.com/p/8e7c697fe1ffd4846832506bdf656931.jpg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (2, 1, 'Bubly BlackBerry', 'Sparkling water beverage paired with natural fruit flavour for a burst of blackberry. No calories, no sweetners, all smiles. Each flavour comes with a different smile and greeting to match its unique personality.','3.00', '9', 70, 'https://www.pepsicobeveragefacts.com/content/image/products-thumbs/bubly_blacbery_12_thumb.png?r=20210205');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 1, 'Farming Karma', 'One fresh apple inside a can. Made with Okanagan Apples. Best served chilled, no sugar added, not from concentrate.', '3.00', '10', 70, 'https://www.farmingkarma.ca/wp-content/uploads/2020/06/karma-img1.png');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 1, 'Coke', 'Bring home the authentic, delicious & refreshing taste of Coca-Cola. For crisps, cold taste, enjoy chilled. Perfect size to be enjoyed with meals, snacking or on the go.', '2.00', '10', 70, 'https://cdn11.bigcommerce.com/s-5bce5hukxg/images/stencil/1280x1280/products/2401/2989/coke355__27172.1580962278.jpg?c=2');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 1, 'Diet Coke', 'Bring home the authentic, delicious & refreshing taste of Coca-Cola with less calories! For crisps, cold taste, enjoy chilled. Perfect size to be enjoyed with meals, snacking or on the go.', '2.00', '7', 70, 'https://cocacola.scene7.com/is/image/cocacola/diet-coke-pdp?wid=270&fmt=png-alpha');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 1, 'Coke Zero', 'Bring home the authentic, delicious & refreshing taste of Coca-Cola with zero sugar! For crisps, cold taste, enjoy chilled. Perfect size to be enjoyed with meals, snacking or on the go.', '2.00', '5', 70, 'https://www.nydailynews.com/resizer/lMpyeyRUUP8PmbfptCX_JCvvVQ4=/800x1355/top/arc-anglerfish-arc2-prod-tronc.s3.amazonaws.com/public/FYQMVH2GFHONZESHQJYABPGTHQ.jpg');


-- clothes store
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 2, 'Black Dress', 'Stylish Maxi dress with a cross neckline perfect for a causal day out. This versatile full-length maxi dress is cut to flatter any body type.', '35.00', '1', 70, 'https://cdn.shopify.com/s/files/1/2158/0979/products/cocoosmidi.jpg?v=1608182784');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 2, 'Black Pants', 'Elasticized cuffs and a straight-fit highlight this cool and comfortably casual take on the classic chino.', '20.00', '5', 70, 'https://media.endclothing.com/media/f_auto,w_600,h_600/prodmedia/media/catalog/product/2/5/25-11-2019_carhartt_sidpant_blackrinsed_i003367-8902_jm_1.jpg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 2, 'Wool Sweater', 'Made of 24Nm/2 fine yarn, this merino wool blended sweater has a wool fiteness of 19um. Universal fit for all.', '70.00', '12', 70, 'https://cdni.llbean.net/is/image/wim/297466_1155_41?hei=1095&wid=950&resMode=sharp2&defaultImage=llbstage/A0211793_2');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 2, 'Red Sweater', 'Double lined hood for added warmth with drawstring. Soft feel and reduced pilling for no loose threads.', '20.00', '9', 70, 'https://www.attraction.com/wp-content/uploads/2020/01/hooded-sweater-unisex-chandail-capuchon-unisexe-red-rouge-attraction-ethica-515-v2.jpg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 2, 'Black Shorts', 'Lightweight and breatheable woven fabrics help workout shorts quick-dry suitable for hand wash, machine wash, tumble dry.', '25.00', '8', 70, 'https://assets.adidas.com/images/w_600,f_auto,q_auto/bc634809504a404c9fe5a98f011afdce_9366/Marathon_20_Shorts_Black_DQ2645_01_laydown.jpg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 2, 'Red Shorts', 'Simple and basic fashionable style, perfect for summer daily wear or any leisure time activities.', '25.00', '2', 70, 'https://www.collinsdictionary.com/images/thumb/shorts_71442211_250.jpg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 2, 'Face Socks', 'Fun face socks made from high-quality polyester fiber and spandex. It will give you maximum comfort and soft simulantaneously!', '10.00', '7', 70, 'https://www.divvyupsocks.com/app/uploads/2019/09/blue-14.png');


-- ice cream store
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 3, 'Vanilla Ice Cream', '1kg tub of ice cream, a sweetened frozen food typically eaten as a snack or dessert.', '10.00', '12', 0, 'https://i.imgur.com/OsmWA6K.jpeg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 3, 'Chocolate Ice Cream', '1kg tub of ice cream, a sweetened frozen food typically eaten as a snack or dessert.', '10.00', '12', 0, 'https://i.imgur.com/U2lTMA1.jpg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 3, 'Mint Ice Cream', '1kg tub of ice cream, a sweetened frozen food typically eaten as a snack or dessert.', '10.00', '12', 0, 'https://i.imgur.com/vLNNTY6.jpeg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 3, 'Strawberry Ice Cream', '1kg tub of ice cream, a sweetened frozen food typically eaten as a snack or dessert.', '10.00', '12', 0, 'https://i.imgur.com/Tuew6ub.jpeg');
INSERT INTO products (category_id, store_id, name, description, price, quantity, discount, thumbnail) VALUES (1, 3, 'Coffee Ice Cream', '1kg tub of ice cream, a sweetened frozen food typically eaten as a snack or dessert.', '10.00', '12', 0, 'https://i.imgur.com/hrxyIu0.gif');

